### ISSUE TITLE
Broken XML document for hostnameAliasMapFile causes exception on startup

### ISSUE THREAD

**Issue by matthiasblaesing** [nb-ldap-explorer/nb-ldap-explorer#3]
Copy from bug:
https://netbeans.org/bugzilla/show_bug.cgi?id=252846

User Comments:
GUEST: no idea.

a.riggio: no details. Happened on start.

a.riggio: Started the program

GUEST: Just launched NetBeans a few times and the same error appeared each time.

ted52452: this error start as open Netbeans 8.2

GUEST: Opening the IDE after one week of inactivity

```
org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
   at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
   at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
   at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:441)
   at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:368)
   at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1436)
   at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:999)
   at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
   at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:117)
   at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
   at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
   at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
   at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
   at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
   at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:649)
Caused: javax.xml.bind.UnmarshalException
 - with linked exception:
[org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.]
   at javax.xml.bind.helpers.AbstractUnmarshallerImpl.createUnmarshalException(AbstractUnmarshallerImpl.java:335)
   at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.createUnmarshalException(UnmarshallerImpl.java:563)
   at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:249)
   at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:214)
   at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:157)
   at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:204)
Caused: java.lang.RuntimeException: javax.xml.bind.UnmarshalException
 - with linked exception:
[org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.]
   at com.google.code.nb_ldap_explorer.ssl_certificate_exception.Installer.restored(Installer.java:65)
   at org.netbeans.core.startup.NbInstaller.loadCode(NbInstaller.java:471)
   at org.netbeans.core.startup.NbInstaller.loadImpl(NbInstaller.java:394)
   at org.netbeans.core.startup.NbInstaller.access$000(NbInstaller.java:105)
   at org.netbeans.core.startup.NbInstaller$1.run(NbInstaller.java:346)
   at org.openide.filesystems.FileUtil$2.run(FileUtil.java:447)
   at org.openide.filesystems.EventControl.runAtomicAction(EventControl.java:127)
   at org.openide.filesystems.FileSystem.runAtomicAction(FileSystem.java:641)
   at org.openide.filesystems.FileUtil.runAtomicAction(FileUtil.java:431)
   at org.openide.filesystems.FileUtil.runAtomicAction(FileUtil.java:451)
   at org.netbeans.core.startup.NbInstaller.load(NbInstaller.java:343)
   at org.netbeans.ModuleManager.enable(ModuleManager.java:1194)
   at org.netbeans.ModuleManager.enable(ModuleManager.java:1017)
   at org.netbeans.core.startup.ModuleList.installNew(ModuleList.java:340)
   at org.netbeans.core.startup.ModuleList.trigger(ModuleList.java:276)
   at org.netbeans.core.startup.ModuleSystem.restore(ModuleSystem.java:301)
   at org.netbeans.core.startup.Main.getModuleSystem(Main.java:181)
   at org.netbeans.core.startup.Main.getModuleSystem(Main.java:150)
   at org.netbeans.core.startup.Main.start(Main.java:307)
   at org.netbeans.core.startup.TopThreadGroup.run(TopThreadGroup.java:123)
   at java.lang.Thread.run(Thread.java:745)
```

**Comment by matthiasblaesing** [comment]
As a workaround remove the defect document (Before you do though, I'd like to get a look at the first line of that file):
1. locate the netbeans userdir (http://wiki.netbeans.org/FaqWhatIsUserdir)
2. remove <nbuserdir>/config/SSLVerifier/hostnameAliasMap.xml
